apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: prometheus-k8s
  name: prometheus-user-workload-grpc-tls
  namespace: openshift-user-workload-monitoring
type: Opaque
