apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-querier
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: 0.20.2
  name: thanos-querier-grpc-tls
  namespace: openshift-monitoring
type: Opaque
