prometheusOperator:
  baseImage: quay.io/coreos/prometheus-operator
  prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader
  configReloaderBaseImage: quay.io/coreos/configmap-reload
prometheusK8s:
  retention: 24h
  baseImage: quay.io/prometheus/prometheus
  externalUrl: https://monitoring-demo.staging.core-os.net/prometheus
  resources:
    requests:
      cpu: 200m
      memory: 2Gi
alertmanagerMain:
  volumeClaimTemplate:
    spec:
      resources:
        requests:
          storage: 15Gi
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: https://monitoring-demo.staging.core-os.net/alertmanager
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
