apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusOperator:
      baseImage: quay.io/coreos/prometheus-operator
      prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader
      configReloaderBaseImage: quay.io/coreos/configmap-reload
    prometheusK8s:
      retention: 24h
      baseImage: quay.io/prometheus/prometheus
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
    alertmanagerMain:
      baseImage: quay.io/prometheus/alertmanager
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
