apiVersion: v1
data:
  ca.crt: ""
  ca.key: ""
  prometheus-server.crt: ""
  prometheus-server.key: ""
  thanos-querier-client.crt: ""
  thanos-querier-client.key: ""
kind: Secret
metadata:
  name: grpc-tls
  namespace: openshift-monitoring
type: Opaque
