apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: telemeter-client-tls
  labels:
    k8s-app: telemeter-client
  name: telemeter-client
  namespace: openshift-monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    k8s-app: telemeter-client
