apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thanos-ruler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-ruler
subjects:
- kind: ServiceAccount
  name: thanos-ruler
  namespace: openshift-user-workload-monitoring
