apiVersion: v1
data:
  service-ca.crt: ""
kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
  name: operator-certs-ca-bundle
  namespace: openshift-monitoring
